<?php /** * Copyright © Magento, Inc. All rights reserved. * See COPYING.txt for license details. */ ?>
<div class="checkout-payment-waiting">
    <?php if ($block->getOrderId()) : ?>
        <?php if ($block->getCanViewOrder()) : ?>
            <p><?= $block->escapeHtml(__('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeUrl($block->getViewOrderUrl()), $block->getOrderId())), ['a', 'strong']) ?></p>
        <?php else : ?>
            <p><?= $block->escapeHtml(__('Your order # is: <span>%1</span>.', $block->getOrderId()), ['span']) ?></p>
        <?php endif; ?>

        <p><?= $block->escapeHtml(__('Your payment is being processed. You will receive an email confirmation once it is completed.')) ?></p>

    <?php endif; ?>
    <?= $block->getAdditionalInfoHtml() ?>
    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= $block->escapeUrl($block->getContinueUrl()) ?>">
                <span><?= $block->escapeHtml(__('Continue Shopping')) ?></span>
            </a>
        </div>
    </div>
</div>
