# codecov.yml
coverage:
  status:
    project:
      default:
        target: 40%
        threshold: 1%
    patch:
      default:
        target: 40%

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false